#!/bin/bash
jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38 \
                             @jupyterlab/hub-extension@0.12 \
                             dask-labextension \
                             jupyter-leaflet

#EOF
